travis:
  secure:
    BINSTAR_TOKEN: WzAhj964Fvay0g8qDfYv6htW3WK5GUIT2FvOE9RnY7puqHmSKwuHA+G5SThXrCWA4egjw7Bjzeo5NfZxCSQTt8Jz9N7JGX3u5RWM6YEiwHCb/ZccaItbKUTnFLNMIkMRVac9LTKlK4gGfyWCzCZF7v6yFsWuCMoIj0vy3jr9ulmApOxfSHNqTT9YL8i5tyQRzcfDHTxOTlWBIPgdHYdb6DYmZVx8ixkAmoIkfv7HDeQNnt74KXhFpqvimRmQcPeFjItx+4N9s8Tk3tipbM1/tGyqW5Z1RltVA1hSiMe5BV18d7bi8aUpmXFjEpaOjdVjPw93P9IHWecS+t28LRwvjaWomjYVWp76oqiNd5nxN70qMQ8EgIXiZ3eLlD6jeLLsm2n4sf7fzvlhvTL+CCBye6eigKVhQ37hDxBRs651Avkj5YQrym5R+X0cZxvjGO6NeBnYnS2d21m8uAT/oVxTbZXSVWnPWNAz6fOd59Dc5DHrkSTqY20iQLACNCPGYMJzKlBYs4pQvNSSZRrhQZlWcQaT4JhPmyeOxfjIC2tjMszIX/ymdF/zt8aWa66YdthWP8iGL/1CDkFhGJQxGZRIQMdExptOD+mGRQ1GNWa3Li8We8uzVTer4Mfdm3pbKk79h33yvyQsgmW2MK9KeWNb1m3B4H0QgPJcFv91bJQA7ic=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
